// AI Glossary terms for Instagram posts
// Auto-generated from DB

export const glossaryTerms = [
  {
    en: "Token",
    sk: "Token",
    explanation: "Základná jednotka textu, s ktorou pracuje jazykový model, napríklad celé slovo, jeho časť alebo jeden znak. Model nečíta vety tak ako človek, ale ako postupnosť tokenov, a vždy predpovedá, ktorý token by mal nasledovať. Podľa počtu tokenov sa určuje, koľko textu model naraz zvládne spracovať aj koľko jeho používanie stojí.",
    slug: "token",
  },
  {
    en: "Prompt",
    sk: "Zadanie (prompt)",
    explanation: "Pokyn, otázka alebo text, ktorý človek zadá umelej inteligencii. Od kvality zadania výrazne závisí kvalita odpovede, a preto vznikol aj pojem prompt engineering. Dobrý prompt obsahuje kontext, cieľ a požadovaný formát výsledku.",
    slug: "prompt",
  },
  {
    en: "Neuron",
    sk: "Umelý neurón",
    explanation: "Najmenšia výpočtová jednotka neurónovej siete, inšpirovaná nervovou bunkou v mozgu. Prijme viacero vstupných čísel, každé vynásobí jeho váhou, sčíta ich a rozhodne, aký signál pošle ďalej. Prepojením obrovského množstva takýchto neurónov vznikajú siete, ktoré rozpoznávajú obrázky alebo píšu texty.",
    slug: "neuron",
  },
  {
    en: "Weight",
    sk: "Váha (parameter)",
    explanation: "Číslo, ktoré určuje, aký silný vplyv má jeden signál v neurónovej sieti na ďalší. Počas tréningu sa váhy postupne upravujú, až kým model nezačne dávať správne výsledky. Keď sa povie, že model má stovky miliárd parametrov, myslia sa tým práve tieto čísla.",
    slug: "weight",
  },
  {
    en: "Embed",
    sk: "Vektorová reprezentácia (embedding)",
    explanation: "Prevod slova, vety alebo obrázka na dlhý rad čísel, ktorý zachytáva jeho význam. Výrazy s podobným významom, napríklad pes a šteňa, sú v tomto číselnom priestore blízko seba. Vďaka tomu dokáže AI vyhľadávať podľa významu, nielen podľa presnej zhody slov.",
    slug: "embed",
  },
  {
    en: "RAG",
    sk: "Generovanie rozšírené o vyhľadávanie",
    explanation: "Technika, pri ktorej AI pred odpoveďou najprv vyhľadá relevantné informácie v dokumentoch, databáze alebo na webe. Tie potom použije ako podklad pre svoju odpoveď. Model tak môže pracovať s aktuálnymi či firemnými údajmi a menej si vymýšľa.",
    slug: "rag",
  },
  {
    en: "Tuning",
    sk: "Dolaďovanie (fine-tuning)",
    explanation: "Dodatočný tréning už hotového modelu na menšom, špecializovanom súbore dát. Model si zachová všeobecné znalosti a navyše sa naučí konkrétnu oblasť, štýl alebo úlohu, napríklad lekársku terminológiu. Je to oveľa lacnejšie a rýchlejšie ako trénovať nový model od nuly.",
    slug: "tuning",
  },
  {
    en: "GAN",
    sk: "Generatívna adverzariálna sieť",
    explanation: "Dvojica neurónových sietí, ktoré proti sebe súťažia: jedna vytvára falošné obrázky a druhá sa ich snaží odhaliť. Navzájom sa tak zlepšujú, až kým nie sú vytvorené obrázky takmer na nerozoznanie od skutočných. Metódu predstavil Ian Goodfellow v roku 2014.",
    slug: "gan",
  },
  {
    en: "GPU",
    sk: "Grafický procesor",
    explanation: "Čip pôvodne určený na vykresľovanie grafiky v počítačových hrách, ktorý dokáže vykonávať tisíce výpočtov súčasne. Práve táto schopnosť ho robí ideálnym na trénovanie a spúšťanie umelej inteligencie. Vďaka obrovskému dopytu po GPU sa ich výrobca NVIDIA stal jednou z najhodnotnejších firiem na svete.",
    slug: "gpu",
  },
  {
    en: "AGI",
    sk: "Všeobecná umelá inteligencia",
    explanation: "Hypotetická umelá inteligencia, ktorá by zvládla akúkoľvek intelektuálnu úlohu na úrovni človeka alebo lepšie, nie iba jednu úzku oblasť. Dnešné systémy sú v mnohých veciach výborné, no či a kedy AGI vznikne, je medzi odborníkmi stále predmetom sporov.",
    slug: "agi",
  },
  {
    en: "GPT",
    sk: "Generatívny predtrénovaný transformer",
    explanation: "Typ jazykového modelu, ktorý generuje text, je vopred natrénovaný na obrovskom množstve dát a postavený na architektúre zvanej transformer. Túto architektúru predstavili výskumníci z Googlu v roku 2017. Skratka sa preslávila vďaka ChatGPT, no označuje celý princíp, nie iba jeden produkt.",
    slug: "gpt",
  },
  {
    en: "Infer",
    sk: "Inferencia",
    explanation: "Fáza, keď už natrénovaný model reálne pracuje, teda odpovedá na otázky alebo rozpoznáva obrázky. Tréning prebehne raz a je mimoriadne náročný, kým inferencia sa deje pri každom jednom použití.",
    slug: "infer",
  },
  {
    en: "Epoch",
    sk: "Epocha",
    explanation: "Jeden úplný prechod modelu cez všetky tréningové dáta. Model sa zvyčajne učí v niekoľkých epochách a s každou sa trochu zlepší. Ak ich je priveľa, naučí sa dáta naspamäť a s novými si neporadí, čo sa nazýva preučenie.",
    slug: "epoch",
  },
  {
    en: "Loss",
    sk: "Stratová funkcia",
    explanation: "Číslo, ktoré počas tréningu meria, ako veľmi sa model mýli. Cieľom tréningu je túto hodnotu čo najviac znížiť postupnou úpravou váh. Dá sa to predstaviť ako zostup z hory v hmle, keď človek robí kroky vždy tam, kde terén klesá.",
    slug: "loss",
  },
  {
    en: "CoT",
    sk: "Reťazec myšlienok",
    explanation: "Technika, pri ktorej model pred odpoveďou rozpíše svoj postup krok za krokom. Výrazne to zlepšuje výsledky pri matematike, logike a zložitých úlohách. Moderné premýšľajúce modely takto uvažujú automaticky ešte predtým, ako odpovedia.",
    slug: "cot",
  },
  {
    en: "MoE",
    sk: "Zmes expertov",
    explanation: "Architektúra, v ktorej sa model skladá z mnohých menších podsietí, takzvaných expertov. Pri spracovaní každého tokenu sa aktivuje iba niekoľko z nich, a to tie, ktoré sa naň hodia najlepšie. Model tak môže byť obrovský, no pri práci spotrebuje len zlomok výpočtového výkonu.",
    slug: "moe",
  },
  {
    en: "Temp",
    sk: "Teplota",
    explanation: "Nastavenie, ktoré určuje, nakoľko náhodne alebo kreatívne model odpovedá. Pri nízkej teplote volí najpravdepodobnejšie slová a odpovede sú presné a predvídateľné. Pri vysokej teplote je odvážnejší a nápaditejší, no zároveň náchylnejší na chyby.",
    slug: "temp",
  },
  {
    en: "Align",
    sk: "Zosúlaďovanie (alignment)",
    explanation: "Oblasť výskumu, ktorá sa snaží zabezpečiť, aby umelá inteligencia konala v súlade s ľudskými hodnotami a zámermi. Rieši, ako zabrániť tomu, aby model škodil, klamal alebo splnil úlohu spôsobom, ktorý nikto nechcel.",
    slug: "align",
  },
  {
    en: "RLHF",
    sk: "Posilňované učenie zo spätnej väzby od ľudí",
    explanation: "Metóda, pri ktorej ľudia porovnávajú viacero odpovedí modelu a označia, ktoré sú lepšie. Z týchto hodnotení sa model učí odpovedať užitočnejšie, zrozumiteľnejšie a bezpečnejšie. Práve táto technika pomohla premeniť jazykové modely na použiteľných asistentov.",
    slug: "rlhf",
  },
  {
    en: "ASI",
    sk: "Umelá superinteligencia",
    explanation: "Hypotetická umelá inteligencia, ktorá by ľudí prekonala prakticky vo všetkom, od vedy cez stratégiu až po kreativitu. Na rozdiel od AGI, ktorá by sa človeku vyrovnala, by bola ďaleko pred ním.",
    slug: "asi",
  },
  {
    en: "Inject",
    sk: "Vloženie škodlivého pokynu (prompt injection)",
    explanation: "Útok, pri ktorom niekto ukryje do textu, webovej stránky alebo e-mailu tajné pokyny určené pre umelú inteligenciu. Model ich môže omylom vykonať a napríklad prezradiť dôverné údaje alebo urobiť nechcenú akciu.",
    slug: "inject",
  },
  {
    en: "Cutoff",
    sk: "Dátum uzávierky znalostí",
    explanation: "Dátum, po ktorom model nemá žiadne informácie, pretože vtedy sa skončil zber jeho tréningových dát. O udalostiach, ktoré sa stali neskôr, nevie nič, pokiaľ si ich nevyhľadá na internete.",
    slug: "cutoff",
  },
  {
    en: "MCP",
    sk: "Protokol kontextu modelu",
    explanation: "Otvorený štandard, ktorý v roku 2024 predstavila firma Anthropic a ktorý umožňuje AI asistentom pripojiť sa k externým nástrojom a dátam, napríklad ku kalendáru, e-mailu či databáze. Často sa prirovnáva ku konektoru USB-C pre umelú inteligenciu.",
    slug: "mcp",
  },
  {
    en: "Window",
    sk: "Kontextové okno",
    explanation: "Maximálne množstvo textu, merané v tokenoch, ktoré model dokáže naraz vidieť a brať do úvahy. Zahŕňa celú konverzáciu, vložené dokumenty aj samotnú odpoveď. Kým prvé modely zvládli iba niekoľko strán, dnešné spracujú naraz celé knihy.",
    slug: "window",
  },
  {
    en: "Memory",
    sk: "Pamäť AI",
    explanation: "Schopnosť asistenta zapamätať si informácie o používateľovi naprieč rôznymi konverzáciami, napríklad meno, prácu či preferencie. Bez nej začína každý rozhovor od nuly, pretože samotný model si nič trvalo neukladá.",
    slug: "memory",
  },
  {
    en: "Hack",
    sk: "Hackovanie odmeny",
    explanation: "Situácia, keď AI nájde spôsob, ako získať vysoké hodnotenie bez toho, aby úlohu skutočne splnila. Známym príkladom je AI v pretekárskej hre, ktorá namiesto dojazdu do cieľa donekonečna krúžila dookola a zbierala body.",
    slug: "hack",
  },
  {
    en: "Quant",
    sk: "Kvantizácia",
    explanation: "Technika, ktorá zmenšuje model tak, že jeho váhy uloží s menšou presnosťou, napríklad namiesto 16 bitov iba 4 bitmi. Model potom zaberie niekoľkonásobne menej pamäte a beží rýchlejšie, pričom stratí len trochu kvality.",
    slug: "quant",
  },
  {
    en: "NPU",
    sk: "Neurónový procesor",
    explanation: "Špeciálny čip určený na výpočty umelej inteligencie, ktorý je dnes súčasťou mnohých mobilov a notebookov. Úlohy ako rozpoznávanie tváre, úprava fotiek či prepis reči zvláda oveľa úspornejšie ako bežný procesor.",
    slug: "npu",
  },
  {
    en: "Open",
    sk: "Otvorený model",
    explanation: "Model umelej inteligencie, ktorého váhy sú voľne zverejnené, takže si ho ktokoľvek môže stiahnuť, spustiť na vlastnom počítači a upraviť. Známymi príkladmi sú modely Llama od firmy Meta, čínsky DeepSeek alebo francúzsky Mistral.",
    slug: "open",
  },
  {
    en: "Confab",
    sk: "Konfabulácia (halucinácia AI)",
    explanation: "Jav, keď model sebavedome vymyslí informáciu, ktorá znie dôveryhodne, no nie je pravdivá, napríklad neexistujúci citát, zdroj či udalosť. Vzniká preto, lebo model predpovedá pravdepodobný text, a nie overuje fakty.",
    slug: "confab",
  },
  {
    en: "Noise",
    sk: "Difúzny model",
    explanation: "Typ modelu, ktorý generuje obrázky tak, že začne z náhodného šumu, podobného zrneniu na starom televízore, a krok za krokom ho čistí, až vznikne obraz podľa zadania. Na tomto princípe fungujú Midjourney, Stable Diffusion aj mnohé generátory videa.",
    slug: "noise",
  },
  {
    en: "Seed",
    sk: "Semienko (seed)",
    explanation: "Číslo, ktoré určuje počiatočnú náhodnosť pri generovaní obrázka alebo textu. S rovnakým promptom a rovnakým semienkom dostanete rovnaký výsledok, s iným semienkom zase inú variáciu.",
    slug: "seed",
  },
  {
    en: "Scrape",
    sk: "Zber dát z webu (scraping)",
    explanation: "Automatické sťahovanie obrovského množstva textov, obrázkov a videí z internetu, na ktorých sa potom trénujú AI modely. Mnohí autori, umelci a médiá s tým nesúhlasia, pretože sa ich diela použili bez povolenia a bez odmeny.",
    slug: "scrape",
  },
  {
    en: "Label",
    sk: "Označovanie dát (anotácia)",
    explanation: "Práca, pri ktorej ľudia ručne označujú dáta, napríklad vyznačujú chodcov na fotkách alebo hodnotia odpovede chatbota. Bez takto pripravených dát by sa AI nemala z čoho správne učiť.",
    slug: "label",
  },
  {
    en: "Bench",
    sk: "Benchmark",
    explanation: "Štandardizovaný test, ktorým sa meria a porovnáva výkon AI modelov, napríklad v matematike, programovaní alebo všeobecných vedomostiach. Firmy sa výsledkami rady chvália pri uvedení každého nového modelu.",
    slug: "bench",
  },
  {
    en: "Arena",
    sk: "AI aréna",
    explanation: "Platforma, kde ľudia zadajú otázku dvom anonymným modelom a hlasujú, ktorá odpoveď je lepšia. Až po hlasovaní sa dozvedia, o ktoré modely išlo. Z miliónov hlasov vzniká rebríček podobný hodnoteniu šachistov.",
    slug: "arena",
  },
  {
    en: "Act",
    sk: "Akt o umelej inteligencii (AI Act)",
    explanation: "Prvý komplexný zákon o umelej inteligencii na svete, ktorý prijala Európska únia v roku 2024 a ktorý platí aj na Slovensku. Rozdeľuje AI systémy podľa miery rizika a niektoré, napríklad sociálne bodovanie občanov, úplne zakazuje.",
    slug: "act",
  },
  {
    en: "Router",
    sk: "Smerovač modelov",
    explanation: "Systém, ktorý podľa náročnosti otázky automaticky rozhodne, ktorý model ju spracuje. Jednoduché otázky pošle rýchlemu a lacnému modelu, zložité zase výkonnejšiemu, ktorý dlhšie premýšľa.",
    slug: "router",
  },
  {
    en: "Detect",
    sk: "Detektor AI textu",
    explanation: "Nástroj, ktorý sa snaží rozpoznať, či text napísal človek alebo umelá inteligencia. Takéto detektory sú však notoricky nespoľahlivé a často falošne obvinia aj ľudí. Firma OpenAI svoj vlastný detektor v roku 2023 dokonca stiahla pre nízku presnosť.",
    slug: "detect",
  },
];
